import glob
import os
# Define input path
input_path = "/scratch/lustre/home/aust0075/Mouse_Aging_data"

samples = ["SRR5642553", "SRR5642554", "SRR5642555", "SRR5642545", "SRR5642544", "SRR5642561"]

# Reference genome files
genome_index_dir = "/scratch/lustre/home/aust0075/Mouse_Aging_data/grcm38/genome_index"
genome_gff = "/scratch/lustre/home/aust0075/Mouse_Aging_data/grcm38_gff3/Mus_musculus.GRCm38.102.gff3"

# Rule all: final target files
rule all:
    input:
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_fastqc.html", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_fastqc.html", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_val_1_fastqc.html", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_val_2_fastqc.html", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_1_val_1.fq.gz", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_2_val_2.fq.gz", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/hisat2/{sample}.bam", sample=samples),
        "/scratch/lustre/home/aust0075/Mouse_Aging/results/counts.txt",
        "/scratch/lustre/home/aust0075/Mouse_Aging/results/multiqc_report.html"

rule trimGalore:
    input:
        fq1 = lambda wildcards: f"{input_path}/{wildcards.sample}_1.fastq.gz",
        fq2 = lambda wildcards: f"{input_path}/{wildcards.sample}_2.fastq.gz"
    output:
        fq1 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_1_val_1.fq.gz",
        fq2 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_2_val_2.fq.gz"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    params:
        quality = 15,
        length = 35
    shell:
        """
        trim_galore --paired -o /scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore \
        -q {params.quality} \
        -j {threads} \
        --length {params.length} \
        {input.fq1} {input.fq2}
        """

rule fastqc:
    input:
        fq1 = lambda wildcards: f"{input_path}/{wildcards.sample}_1.fastq.gz",
        fq2 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_1_val_1.fq.gz",
        fq3 = lambda wildcards: f"{input_path}/{wildcards.sample}_2.fastq.gz",
        fq4 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_2_val_2.fq.gz"

    output:
        html1 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_fastqc.html",
        html2 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_val_1_fastqc.html",
        html3 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_fastqc.html",
        html4 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_val_2_fastqc.html",
        zip1 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_fastqc.zip",
        zip2 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_val_1_fastqc.zip",
        zip3 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_fastqc.zip",
        zip4 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_val_2_fastqc.zip"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    shell:
        """
        fastqc -t {threads} --outdir /scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc {input.fq1} {input.fq2} {input.fq3} {input.fq4}
        """

rule hisat2:
    input:
        fq1 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_1_val_1.fq.gz",
        fq2 = "/scratch/lustre/home/aust0075/Mouse_Aging/results/trim_galore/{sample}_2_val_2.fq.gz"
    output:
        sam = "/scratch/lustre/home/aust0075/Mouse_Aging/results/hisat2/{sample}.sam",
        bam = "/scratch/lustre/home/aust0075/Mouse_Aging/results/hisat2/{sample}.bam",
        bai = "/scratch/lustre/home/aust0075/Mouse_Aging/results/hisat2/{sample}.bam.bai",
        stat = "/scratch/lustre/home/aust0075/Mouse_Aging/results/hisat2/{sample}_hisat2.stat"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    shell:
        """
        hisat2 -p {threads} -x {genome_index_dir} --no-unal -1 {input.fq1} -2 {input.fq2} -S {output.sam} --new-summary --summary-file {output.stat}
        samtools view -@ {threads} -bS {output.sam} | samtools sort -@ {threads} -o {output.bam} 
        samtools index {output.bam}
        """

rule featureCounts:
    input:
        bam = expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/hisat2/{sample}.bam", sample=samples)
    output:
        counts = "/scratch/lustre/home/aust0075/Mouse_Aging/results/counts.txt",
        stats = "/scratch/lustre/home/aust0075/Mouse_Aging/results/counts.txt.summary"
    conda: "envs/preprocess_rnaseq.yaml"
    threads: 4
    shell:
        """
        featureCounts -a {genome_gff} -F GTF -t CDS -g Parent -o {output.counts} -s 0 -T {threads} -p --countReadPairs -B {input.bam}
        """
        
rule multiqc:
    input:
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_fastqc.zip", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_fastqc.zip", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_1_val_1_fastqc.zip", sample=samples),
        expand("/scratch/lustre/home/aust0075/Mouse_Aging/results/fastqc/{sample}_2_val_2_fastqc.zip", sample=samples),
        "/scratch/lustre/home/aust0075/Mouse_Aging/results/counts.txt.summary"
    output:
        "/scratch/lustre/home/aust0075/Mouse_Aging/results/multiqc_report.html",
        directory("/scratch/lustre/home/aust0075/Mouse_Aging/results/multiqc_data")
    conda: "envs/preprocess_rnaseq.yaml"
    shell:
        """
        multiqc --outdir /scratch/lustre/home/aust0075/Mouse_Aging/results/ {input}
        """