reference:
  genome: "mm10"
  bowtie2_index: "data/reference/bowtie2_index/mm10"

params:
  alignment:
    bowtie2: "--very-sensitive --no-unal --phred33"
  chipseq:
    macs2: "--nomodel --extsize 200 --qvalue 0.05 --broad"
    #blacklist: "data/reference/mm10-blacklist.v2.bed"

samples: "config/samples.tsv"
