samples: "config/samples.csv"

reference:
  genome: "mm10"
  fasta: "data/reference/mm10.fa"
  gtf: "data/reference/mm10.gtf"
  star_index: "data/reference/star_index"
  bowtie2_index: "data/reference/bowtie2_index"

chipseq:
  macs2_params: "--broad --nomodel --extsize 147 -q 0.05"

rnaseq:
  strandedness: "forward"
